### PR TITLE
ADX 1007 - Update frontend to align with HIV Tools SSO

### PR DESCRIPTION
**Pull request by A-Souhei**
## Description
Added bootstrap 5 layout and classes to Jinja template profile.html

image
New UI:

image
image

The Auth0 css if from [here](https://github.com/auth0/lock.git)

## Checklist

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request).
You may not need to check all boxes.

- [x] The Jira ticket for this issue has been updated to "Ready to Review" or equivalent.
- [x] I have developed these changes in discussion with the appropriate project manager.
- [ ] My code follows the general Fjelltopp documentation (see Confluence).
- [ ] I have made corresponding changes to the Fjelltopp documentation (see Confluence).
- [ ] I have rebased this branch with master.
- [ ] New dependency changes have been committed.
- [ ] I have added automated tests that prove my fix is effective or that my feature works.
- [x] New and existing tests pass locally with my changes.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own code.
- [x] I have assigned at least one reviewer.

### CODE REVIEW

**Review by kforenc — CHANGES_REQUESTED** [review]
It looks great! :) Please demo it to Tomek so he can add his comments.
I have 2 comments:
1. If it's quick (less than 2 hours) please make error messages more similar to those that appear when you try signing up and type wrong data.
2. Can we make 'flash' messages in a green rectangle, like in https://i.stack.imgur.com/XaU8E.png (without 'x' to close it, and in green).

**Comment by A-Souhei** [comment]
Fixed

**Review by kforenc — APPROVED** [review]
Nicely done. I like it :).

**Comment by tomeksabala** [comment]
image

**Review by kforenc — APPROVED** [review]
Looks beautiful. Good job!

**Review by tomeksabala — APPROVED** [review]

**Pull request merged**
